cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'folkloreatelier/fonts'

brew 'ack'
brew 'coreutils'
brew 'css3-font-converter'
brew 'ffmpeg', args: ['with-faac', 'with-freetype', 'with-ffplay', 'with-libssh', 'with-libvorbis', 'with-libvpx', 'with-openjpeg', 'with-speex', 'with-rtmpdump', 'with-theora', 'with-webp', 'with-x265']
brew 'go'
brew 'git'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'homebrew/php/php70'
brew 'lame'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'mysql'
brew 'nvm'
brew 'node'
brew 'openssl'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '1password'
cask 'adium'
cask 'atom'
cask 'firefox'
cask 'garmin-express'
cask 'google-chrome'
cask 'handbrake'
cask 'mapbox-studio'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
