cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'folkloreatelier/fonts'


brew 'ack'
brew 'ansible'
brew 'awscli'
brew 'aws-elasticbeanstalk'
brew 'composer'
brew 'coreutils'
brew 'css3-font-converter'
brew 'dockutil'
brew 'ffmpeg'
brew 'git'
brew 'git-lfs'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'kops'
brew 'kubectl'
brew 'kubernetes-helm'
brew 'kube-aws'
brew 'lame'
brew 'libcaca'
brew 'libgit2'
brew 'minikube'
brew 'mysql'
brew 'openssl'
brew 'packer'
brew 'php@7.3'
brew 'php@7.4'
brew 'php@8.0', link: true
brew 'postgresql'
brew 'python', link: true
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'terraform'
brew 'tmux'
brew 'transmission'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
brew 'wakeonlan'
brew 'awscli'
brew 'platformio'
brew 'numpy'
brew 'starship'

cask '1password'
cask '1password-cli'
# cask 'arq'
cask 'airfoil'
cask 'android-sdk'
cask 'arduino'
# cask 'atom'
cask 'cyberduck'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
# cask 'google-photos-backup-and-sync'
# cask 'google-cloud-sdk'
cask 'harvest'
cask 'iterm2'
# cask 'minikube'
cask 'loopback'
cask 'microsoft-teams'
cask 'obs'
# cask 'openemu'
cask 'poedit'
# cask 'postman'
# cask 'processing'
cask 'sequel-pro'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'spotify'
# cask 'teamviewer'
cask 'texturepacker'
cask 'vlc'
cask 'vagrant'
cask 'spectacle'
cask 'coolterm'
cask 'blender'
cask 'hex-fiend'
cask 'virtualbox'
cask 'vlc'
cask 'zoomus'
cask 'xquartz'
cask 'handbrake'
cask 'insomnia'
cask 'discord'
cask 'visual-studio-code'
