cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'folkloreatelier/fonts'

cask 'java'
cask 'xquartz'

brew 'ack'
brew 'ansible'
brew 'awscli'
brew 'awsebcli'
brew 'composer'
brew 'coreutils'
brew 'css3-font-converter'
brew 'dockutil'
brew 'ffmpeg', args: ['with-faac', 'with-freetype', 'with-ffplay', 'with-libssh', 'with-libvorbis', 'with-libvpx', 'with-openjpeg', 'with-speex', 'with-rtmpdump', 'with-theora', 'with-webp', 'with-x265']
brew 'git'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'kops'
brew 'kubectl'
brew 'kubernetes-helm'
brew 'kube-aws'
brew 'lame'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'mysql'
brew 'openssl'
brew 'packer'
brew 'php@7.0', link: true
brew 'php@7.1'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'terraform'
brew 'tmux'
brew 'transmission'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
brew 'wakeonlan'

cask '1password'
cask '1password-cli'
cask 'arq'
cask 'android-sdk'
# cask 'android-studio'
cask 'arduino'
cask 'atom'
cask 'cyberduck'
cask 'docker'
cask 'dropbox'
cask 'etcher'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'google-photos-backup-and-sync'
cask 'google-cloud-sdk'
cask 'harvest'
cask 'iterm2'
cask 'minikube'
cask 'openemu'
cask 'poedit'
cask 'postman'
cask 'processing'
cask 'sequel-pro'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'teamviewer'
cask 'texturepacker'
cask 'virtualbox'
cask 'vlc'
cask 'vagrant'
