apm install editorconfig
apm install git-plus
apm install file-icons
apm install advanced-open-file
apm install autocomplete-python
apm install blade-snippets
apm install darkula-ui
apm install docblockr
apm install dracula-theme
apm install jsonlint
apm install language-blade
apm install laravel
apm install linter
apm install linter-eslint
apm install linter-phpcs
apm install linter-pylama
apm install linter-sass-lint
apm install minimap
apm install open-recent
apm install pigments
apm install react
apm install sort-lines
apm install todo-show
apm install toggle-quotes
